### ISSUE TITLE
Implement FUNC_CODE_INST_FENCE

### ISSUE THREAD

**Issue by atomb** [GaloisInc/llvm-pretty-bc-parser#12]
See [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/src/Data/LLVM/BitCode/IR/Function.hs)

**Comment by siddharthist** [comment]
Implemented in https://github.com/siddharthist/llvm-pretty-bc-parser/commit/db600fb8279d0a777de94110fba58473a61eab9e, modulo a `TODO` affecting several concurrency-related instructions.
