### ISSUE TITLE
Match Failed with clang version 7.0.1 (tags/RELEASE_701/final)

### ISSUE THREAD

**Issue by pedrotst** [GaloisInc/llvm-pretty-bc-parser#128]
When I compile [this file](https://gitlab-int.galois.com/saw/saw-intro/blob/master/examples/ffs.c) with clang version 7.0.1 (tags/RELEASE_701/final), and try to `llvm_load_module` I get the following error:
```
saw: user error (Bitcode parsing of ffs.bc failed:match failed)
```
Attached you can find the .bc file generated by clang:
[ffs.tar.gz](https://github.com/GaloisInc/llvm-pretty-bc-parser/files/3159273/ffs.tar.gz)

**Comment by siddharthist** [comment]
When I compile the C from source and run `llvm-disasm`, it works fine. It appears that this bitcode is invalid:
```
 tar xvf ffs.tar.gz && nix-shell --pure -p llvm_7 --run "llvm-dis *.bc"
./ffs.bc
llvm-dis: error: Invalid bitcode signature
```

**Comment by pedrotst** [comment]
I might have sent an old version of the compiled version, please try again with this one


[ffs.tar.gz](https://github.com/GaloisInc/llvm-pretty-bc-parser/files/3159376/ffs.tar.gz)

**Comment by siddharthist** [comment]
That one works just fine with both LLVM's disassembler (`llvm-dis`) and this projects' (`llvm-disasm`). 

The issue seems to be that @pedrotst was using a very old version of SAW (0.2, ~2016).
