### ISSUE TITLE
Implement FUNC_CODE_INST_CMPXCHG

### ISSUE THREAD

**Issue by atomb** [GaloisInc/llvm-pretty-bc-parser#13]
See [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/src/Data/LLVM/BitCode/IR/Function.hs)

**Comment by siddharthist** [comment]
I have made some progress on this, but it's unfinished: https://github.com/siddharthist/llvm-pretty-bc-parser/tree/cmpxchg
