### ISSUE TITLE
Error when parsing SQLite 3.32.1 with Clang 10: Instruction code 56 is unknown

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/llvm-pretty-bc-parser#148]
I see that Clang 10 is not yet listed in the README as supported, so this might be known but just wanted to raise it if not.
```
$ clang --version
clang version 10.0.1                             
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/dgpd1y26p9vfs5j382cw6wyblsc0q3cl-clang-10.0.1/bin
```
```
      Exception: LLVMParseError (Error {errContext = ["@sqlite3_str_vappendf","FUNCTION_BLOCK","FUNCTION_BLOCK_ID","value symbol table","MODULE_BLOCK","Bitstream"], errMessage = "instruction code 56 is unknown"})
```
[sqlite-3.32.1.bc.zip](https://github.com/GaloisInc/llvm-pretty-bc-parser/files/6013842/sqlite-3.32.1.bc.zip)

**Comment by RyanGlScott** [comment]
Instruction code 56 corresponds to the [`fneg`](https://releases.llvm.org/12.0.0/docs/LangRef.html#fneg-instruction) instruction. Here is a simpler way to trigger it (using Clang 10.0.0-4ubuntu1):

```c
double negate(double x) {
  return -x;
}

int main() {
  return 0;
}
```
```
$ crux-llvm test2.c
instruction code 56 is unknown
from:
        @negate
        FUNCTION_BLOCK
        FUNCTION_BLOCK_ID
        value symbol table
        MODULE_BLOCK
        Bitstream
```

**Comment by kquick** [comment]
See also issue #158 158.  There is also active work being done on this by @Ptival .

**Comment by RyanGlScott** [comment]
Luckily, `fneg` is the only missing piece needed to parse the original SQLite example. I have submitted #159 with a fix, which includes a more minimal test case.
