### ISSUE TITLE
Implement FUNC_CODE_INST_STOREATOMIC

### ISSUE THREAD

**Issue by atomb** [GaloisInc/llvm-pretty-bc-parser#17]
See [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/src/Data/LLVM/BitCode/IR/Function.hs)

**Comment by siddharthist** [comment]
Fixed in https://github.com/GaloisInc/llvm-pretty-bc-parser/commit/473d7b54cfefc29f63a2885d71268f299df607a4
