### ISSUE TITLE
support `FUNC_CODE_INST_ATOMICRMW`

### ISSUE THREAD

**Issue by Ptival** [GaloisInc/llvm-pretty-bc-parser#175]

**Comment by marcgalois** [comment]
Here's code to reproduce this situation:

Using `rustc 1.56.0 (09c42c458 2021-10-18)`

```rust
use std::sync::atomic::*;

pub fn blarg(x: &AtomicU32) {
    x.fetch_and(0xfe, Ordering::Relaxed);
}
```

with the compile command
```
rustc --emit=llvm-bc test.rs --crate-type lib
```

**Comment by RyanGlScott** [comment]
This function code was introduced in https://github.com/llvm/llvm-project/commit/ad90a6be219a547873beb80f977e45e23e9247ac. `FUNC_CODE_INST_ATOMICRMW` is nearly identical to the existing `FUNC_CODE_INST_ATOMICRMW_OLD` (which `llvm-pretty-bc-parser` does support), except that the former encodes a type for the `val` field, whereas the latter does not. Accordingly, LLVM reuses almost the same code to parse both `FUNC_CODE_INST_ATOMICRMW` and `FUNC_CODE_INST_ATOMICRMW_OLD`, so `llvm-pretty-bc-parser` likely could too.

**Comment by RyanGlScott** [comment]
Another way to encounter this function code with just `clang` (version 13 or higher) is with this program:

```c
#include <stdint.h>

uint32_t blarg(uint32_t x) {
  return __sync_fetch_and_and(&x, 0xfe);
}
```

After compiling that with `clang test.c -emit-llvm -c`, you'll get:

```
λ> parseBitCodeFromFile "test.bc"
Left (Error {errContext = ["@blarg","FUNCTION_BLOCK","FUNCTION_BLOCK_ID","value symbol table","MODULE_BLOCK","Bitstream"], errMessage = "instruction code 59 is unknown"})
```

**Comment by RyanGlScott** [comment]
This ended up being relatively straightforward to support. I've submitted #182 with a patch.
