### ISSUE TITLE
Support `CST_CODE_INLINEASM` constant codes added in LLVM 13 and 14

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/llvm-pretty-bc-parser#184]
Prior to LLVM 13, there were two constant codes (18 and 23) for inline assembly statements. There are now two more such codes as of LLVM 14:

* Code 28 (now named `CST_CODE_INLINEASM_OLD3`), added in LLVM 13 in https://github.com/llvm/llvm-project/commit/8ec9fd483949ca3b23053effcac226dcc56e7a95
* Code 30 (now named `CST_CODE_INLINEASM`), added in LLVM 14 in https://github.com/llvm/llvm-project/commit/62b1682570b1059e8c6542192159dcde32c13c30

Currently, `llvm-pretty-bc-parser` does not support either of these. Here is a test case:

```c
int main() {
  asm("nop");
  return 0;
}
```

When compiled with `~/Software/clang+llvm-13.0.1/bin/clang test.c -c -emit-llvm`, this produces the following parse error:

```
λ> parseBitCodeFromFile "test.bc"
Left (Error {errContext = ["CONSTANTS_BLOCK","@main","FUNCTION_BLOCK","FUNCTION_BLOCK_ID","value symbol table","MODULE_BLOCK","Bitstream"], errMessage = "Unknown constant record code 28\nAre you sure you're using a supported compiler?\nCheck here: https://github.com/GaloisInc/llvm-pretty-bc-parser\n"})
```

The error is much the same when compiled with LLVM 14, except that the code will be 30 instead of 28.

With some effort, we should be able to adapt the existing `llvm-pretty-bc-parser` code for code 18 (now named `CST_CODE_INLINEASM_OLD` as of LLVM 14):

https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/daffc926d526c51ba7967865ec4b713aafd0941f/src/Data/LLVM/BitCode/IR/Constants.hs#L360-L373

And for code 23 (now named `CST_CODE_INLINEASM_OLD2` as of LLVM 14):

https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/daffc926d526c51ba7967865ec4b713aafd0941f/src/Data/LLVM/BitCode/IR/Constants.hs#L416-L437

**Comment by RyanGlScott** [comment]
@eddywestbrook also notes that this bug is triggered when compiling the following program with `rustc-1.60.0` (bundled with LLVM 14):

```rs
/* A function that immediately panics */
pub fn get_out () -> ! {
    panic!("Uh oh!")
}
```

This is because the generated LLVM bitcode will use inline assembly, somewhat surprisingly:

```ll
; Function Attrs: inlinehint uwtable
define void @_ZN4core4hint9black_box17haf534fee2d513d5fE() unnamed_addr #0 {
start:
  call void asm sideeffect "", "r,~{memory}"({}* undef), !srcloc !7
  br label %bb1

bb1:                                              ; preds = %start
  ret void
}
```

**Comment by RyanGlScott** [comment]
Note that:

* Code 28 (`CST_CODE_INLINEASM_OLD3`) adds an `unwind` flag
* Code 30 (`CST_CODE_INLINEASM`) adds a function type

In order to support this new information, we will need to augment the [`ValAsm`](https://github.com/elliottt/llvm-pretty/blob/34c95e77fb9fdc584c23208f81f6072cb0e05c3f/src/Text/LLVM/AST.hs#L994) data constructor in `llvm-pretty` with additional fields.

**Comment by langston-barrett** [comment]
These constants also appear when compiling an x86_64 "tinyconfig" Linux kernel 5.17 with LLVM 13 [like so](https://gist.github.com/langston-barrett/67863fa789cd66e69af971644c28e04a). Bitcode: [vmlinux-5.17-llvm-13.bc.zip](https://github.com/GaloisInc/llvm-pretty-bc-parser/files/8582982/vmlinux-5.17-llvm-13.bc.zip).
