### ISSUE TITLE
Implement FUNC_CODE_LANDINGPAD

### ISSUE THREAD

**Issue by atomb** [GaloisInc/llvm-pretty-bc-parser#19]
See [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/src/Data/LLVM/BitCode/IR/Function.hs)

**Comment by siddharthist** [comment]
This was done in https://github.com/GaloisInc/llvm-pretty-bc-parser/commit/2e8f839187fa67abdda5f33082aa9a1fb201560b
