### ISSUE TITLE
Error when parsing Rust IR containing pointers

### ISSUE THREAD

**Issue by aisamanra** [GaloisInc/llvm-pretty-bc-parser#2]
Parsing IR produced by the Rust compiler tends to fail if the functions use references or pointers. The actual error raised is:

````
Bitcode parsing of add.bc failed:
unknown record code: 3
  from:
        METADATA_BLOCK
        MODULE_BLOCK
````

Example output from `rustc` that produces this issue is posted [here](https://gist.github.com/aisamanra/9615082f33dd23d601aa) in both IR and bitcode form.

**Comment by elliottt** [comment]
The example parses now, and I've updated the test suite to reflect the bug.
