### ISSUE TITLE
Build with GHC 9.4, 9.6

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/llvm-pretty-bc-parser#224]
There are two more recent major versions of GHC available: https://www.haskell.org/ghc/download.html

**Comment by RyanGlScott** [comment]
`llvm-pretty-bc-parser` should already build with GHC 9.4. (It it doesn't, then something is very wrong.)

To make it compatible with GHC 9.6, we will need to do some light import rearrangement to handle `mtl-2.3.*`, which no longer re-exports things from `Control.Monad`. I have a WIP branch [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/compare/ghc-9.6) for this. Before I submit this, I'd like to first land https://github.com/elliottt/llvm-pretty/pull/112, which performs one upper version bump on the `llvm-pretty` side.

**Comment by langston-barrett** [comment]
> llvm-pretty-bc-parser should already build with GHC 9.4. 

Ah, then perhaps we just need a little readme and CI update to reflect this! 

https://github.com/GaloisInc/llvm-pretty-bc-parser#ghc-support

https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/.github/workflows/build.yml#L26

**Comment by RyanGlScott** [comment]
Ah, right. As I recall, `llvm-pretty-bc-parser` worked out of the box with GHC 9.4 with no additional changes required, so I neglected to update anything. I'll make sure to make up for lost time when updating to support GHC 9.6.
