### ISSUE TITLE
Instruction metadata is not attached

### ISSUE THREAD

**Issue by kquick** [GaloisInc/llvm-pretty-bc-parser#246]
Some instructions can have metadata attached.  For example in, `br label %5, !dbg !3, !llvm.loop !4` the `!llvm.loop !4` is attached metadata.

The llvm-pretty-bc-parser frequently drops this attached metadata, presenting only `br label %5, !dbg !3` as a result of parsing.

**Comment by RyanGlScott** [comment]
This is (hopefully) fixed with #244.
