### ISSUE TITLE
Error when parsing optimized IR

### ISSUE THREAD

**Issue by aisamanra** [GaloisInc/llvm-pretty-bc-parser#3]
Turning on optimizations in certain cases cases a distinct parse error within deeply nested records. In this case, this was generated from the same Rust source as #2 but with optimizations turned on, but @TomMD reliably informs me that similar problems come up with C compiled with -O3. (The simple examples I've tried haven't yielded this problem yet, but if one comes up I will include it.)

The LLVM IR/bitcode is [here](https://gist.github.com/aisamanra/5bf4e0b72ffd3c58104d), and the error message is:

````
unable to parse record field 1 of record Record {recordCode = 1, recordFields = [FieldArray [FieldFixed (BitString {bsLength = 8, bsData = 95}),FieldFixed (BitString {bsLength = 8, bsData = 90}),FieldFixed (BitString {bsLength = 8, bsData = 78}),FieldFixed (BitString {bsLength = 8, bsData = 51}),FieldFixed (BitString {bsLength = 8, bsData = 97}),FieldFixed (BitString {bsLength = 8, bsData = 100}),FieldFixed (BitString {bsLength = 8, bsData = 100}),FieldFixed (BitString {bsLength = 8, bsData = 49}),FieldFixed (BitString {bsLength = 8, bsData = 48}),FieldFixed (BitString {bsLength = 8, bsData = 95}),FieldFixed (BitString {bsLength = 8, bsData = 95}),FieldFixed (BitString {bsLength = 8, bsData = 114}),FieldFixed (BitString {bsLength = 8, bsData = 117}),FieldFixed (BitString {bsLength = 8, bsData = 115}),FieldFixed (BitString {bsLength = 8, bsData = 116}),FieldFixed (BitString {bsLength = 8, bsData = 95}),FieldFixed (BitString {bsLength = 8, bsData = 97}),FieldFixed (BitString {bsLength = 8, bsData = 98}),FieldFixed (BitString {bsLength = 8, bsData = 105}),FieldFixed (BitString {bsLength = 8, bsData = 69})]]}
  from:
        METADATA_STRING
        METADATA_BLOCK
        MODULE_BLOCK
````

**Comment by TomMD** [comment]
As @aisamanra  said, somewhat similar errors (unrecognized opcodes) occur when loading bytecode for tweetnacl.c compiled with `clang -O2 -emit-llvm`.  I can get details if that would help.

**Comment by elliottt** [comment]
The example parses now, and I've updated the test suite to reflect the bug.
