### ISSUE TITLE
Implement METADATA_IMPORTED_ENTITY

### ISSUE THREAD

**Issue by atomb** [GaloisInc/llvm-pretty-bc-parser#37]
See [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/src/Data/LLVM/BitCode/IR/Metadata.hs)

**Comment by siddharthist** [comment]
This was closed in https://github.com/GaloisInc/llvm-pretty-bc-parser/commit/93ffab13c804764fe7c2cb1fa29dfc0e0baa67e9
