### ISSUE TITLE
Implement METADATA_GLOBAL_DECL_ATTACHMENT

### ISSUE THREAD

**Issue by atomb** [GaloisInc/llvm-pretty-bc-parser#41]
See [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/src/Data/LLVM/BitCode/IR/Metadata.hs)

**Comment by elliottt** [comment]
Compiling this program with `clang-5.0.0` will trigger this case:
```c
#include "csmith.h"
a;
char *b;
main() { crc32_gentab; }
```

**Comment by elliottt** [comment]
Should be fixed as of 2ed7b452d8c510a87ebf74a843fade912978cd5b.
