### ISSUE TITLE
Implement METADATA_INDEX_OFFSET

### ISSUE THREAD

**Issue by atomb** [GaloisInc/llvm-pretty-bc-parser#43]
See [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/src/Data/LLVM/BitCode/IR/Metadata.hs)

**Comment by elliottt** [comment]
Which version of llvm was producing this? It looks like llvm-3.9.1 doesn't include that metadata code anymore, so it might not be necessary to implement it anymore.

**Comment by atomb** [comment]
It seems as though the following program, compiled with ` clang-4.0 -O -w -g `, includes this entry type.

````
#include "csmith.h"
a;
char *b;
main() { crc32_gentab; }
````

**Comment by elliottt** [comment]
Ah, thanks!

**Comment by elliottt** [comment]
The fix was to skip this entry, as it's used when lazy-loading metadata. As we don't support that, and read everything in at once, it's easier to just skip over it.
