### ISSUE TITLE
Implement METADATA_INDEX

### ISSUE THREAD

**Issue by atomb** [GaloisInc/llvm-pretty-bc-parser#44]
See [here](https://github.com/GaloisInc/llvm-pretty-bc-parser/blob/master/src/Data/LLVM/BitCode/IR/Metadata.hs)

**Comment by elliottt** [comment]
The fix was to skip this entry, as it's used when lazy-loading metadata. As we don't support that, and read everything in at once, it's easier to just skip over it.
